[package]
name = "Marketplace"
version = "0.0.0"

[addresses]
marketplace = "_"

[dependencies]
SupraFramework = { local = "../../framework/supra-framework" }
AptosToken = { local = "../../framework/aptos-token" }
AptosTokenObjects = { local = "../../framework/aptos-token-objects" }
