[build]
default-target = "x86_64-unknown-linux-gnu"
pre-build = [
  "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH git protobuf-compiler tmux g++ libgmp-dev cmake clang lld libudev-dev",
  "dpkg --add-architecture $CROSS_DEB_ARCH",
]

[build.env]
passthrough = ["RUSTFLAGS"]
