[package]
name = "ManagedFungibleAsset"
version = "0.0.0"

[addresses]
aptos_framework = "0x1"
aptos_token_objects = "0x4"
example_addr = "_"

[dependencies]
SupraFramework = { local = "../../../framework/supra-framework" }
AptosTokenObjects = { local = "../../../framework/aptos-token-objects" }
