[package]
name = "NFTDAO"
version = "0.0.0"
upgrade_policy = "immutable"

[addresses]
dao_platform = "_"
aptos_framework = "0x1"

[dependencies]
SupraFramework = { local = "../../../framework/supra-framework" }
AptosToken = { local = "../../../framework/aptos-token" }
