[package]
name = "DrandLottery"
version = "0.0.1"

[dependencies]
SupraFramework = { local = "../../framework/supra-framework" }
#AptosStdlib = { local = "../../framework/aptos-stdlib" }

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
drand = "_"
