[package]
name = "Hero"
version = "0.0.0"

[addresses]
hero = "_"

[dependencies]
SupraFramework = { local = "../../../framework/supra-framework" }
AptosTokenObjects = { local = "../../../framework/aptos-token-objects" }
