[package]
name = 'guild'
version = '1.0.0'

[addresses]
guild = "_"

[dependencies]
SupraFramework = { local = "../../../framework/supra-framework" }
AptosTokenObjects = { local = "../../../framework/aptos-token-objects" }
