[package]
name = 'token_lockup'
version = '1.0.0'

[addresses]
token_lockup = "_"

[dependencies]
SupraFramework = { local = "../../../framework/supra-framework" }
AptosTokenObjects = { local = "../../../framework/aptos-token-objects" }
