[package]
name = 'knight'
version = '1.0.0'

[addresses]
knight = "_"

[dependencies]
SupraFramework = { local = "../../../framework/supra-framework" }
AptosTokenObjects = { local = "../../../framework/aptos-token-objects" }
