[package]
name = "package_manager"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies]
SupraFramework = { local = "../../framework/supra-framework" }

[addresses]
deployer = "_"
package = "_"
