[package]
name = 'ambassador'
version = '1.0.0'

# do not change to "_", concrete address needed for module-publish testing framework
[addresses]
ambassador = "0xCAFE"

[dependencies]
SupraFramework = { local = "../../../framework/supra-framework" }
AptosTokenObjects = { local = "../../../framework/aptos-token-objects" }
