[package]
name = "VeiledCoin"
version = "0.0.1"

[dependencies]
SupraFramework = { local = "../../framework/supra-framework" }

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
veiled_coin = "_"
