name: Run aptos framework checks

on:
  push:
    branches: 
        - master
        - integrate_consensus_key
  pull_request:
    branches:
        - master
        - integrate_consensus_key

env:
  CARGO_TERM_COLOR: always
  CARGO_BIN: ~/.cargo/bin/cargo
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  FORGE_BIN: ~/.foundry/bin/forge
  SUI_BIN: ~/.cargo/bin/sui
  APTOS_BIN: ~/.local/bin/aptos
  SCRYPTO_BIN: ~/.cargo/bin/scrypto

jobs:
  build:

    runs-on: org-qa-runner

    steps:

    - uses: actions/checkout@v4
      with:
        clean: false

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42
 
    - name: Run tests
      run: |
        ${{ env.CARGO_BIN }} test --release -p supra-framework -- --skip prover
        ${{ env.CARGO_BIN }} nextest run -p e2e-move-tests
