name: Rust

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          sudo apt install -y lld build-essential pkg-config libudev-dev cmake libclang-dev libssl-dev gparted nload python3-pip net-tools logind curl git chrony htop acl protobuf-compiler g++ libgmp-dev
          cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
